### PR TITLE
Merge to Production

### PR DESCRIPTION
**Pull request by jonasanker**
- Include User data when querying Leaderboard Statistics (#102)

### CODE REVIEW

**Review by TTA777 — COMMENTED** [review]
So the new docker configuration for development does not seem to work on my machine, though this could be because I am using redhat linux, which has a few quirks every once in a while. You have verified it to work for you I take it?

**Comment by jonasanker** [comment]
@TTA777 I believe both Frederik and I got the image to work. What error do you get?

**Comment by TTA777** [comment]
@jonasanker Looked into it a bit more, and turns out it was SeLinux causing the issue. I've got it working now

**Comment by jonasanker** [comment]
@TTA777 The branch not being up to date is not due to content but merge commits. I think you can go ahead and approve

**Review by TTA777 — APPROVED** [review]
lgtm

**Pull request merged**
